background_opacity 1
background #2b2b2b
foreground #e1d1a8

# Font utama
font_family      JetBrains Mono Nerd Font
font_size        10.0

# Kalau mau bold & italic jelas
bold_font        auto
italic_font      auto

cursor_trail 4
cursor_trail_start-threshold 0
cursor_tray_decay 0.1 0.4
cursor_blink true
cursor_shape block

window_padding_width 13